version = 0.1

[default.deploy.parameters]
stack_name = "stage-printer-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xfdaipcxvvw6"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"

