version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli

  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam deploy --config-file pipeline/dev/samconfig.toml --no-confirm-changeset --no-fail-on-empty-changeset
artifacts:
  files:
    - template.yaml
